### ISSUE TITLE
インストール時に実行されたプラグインが機能しない。

### ISSUE THREAD

**Issue by BentleyBentayga** [paralleltree/Ched#53]
![image](https://user-images.githubusercontent.com/94912171/148011415-91962bfe-946f-49cc-b124-560c0c2ad70d.png)
プロセカノートテクスチャをプレビューできないのはなぜですか？
![image](https://user-images.githubusercontent.com/94912171/148011485-9a9bb244-79f7-45f7-9682-482bef7476a9.png)
susファイルのインポートに失敗したのはなぜですか？

これらは非常に煩わしくなり、プラグインはこの厄介な問題のために私にとって非常に役に立たないです！

**Comment by paralleltree** [comment]
The owner of first plugin is not me so I don't know why you face such error.
However, you can open `import_exception.json` in the directory that `Ched.exe` exists to know what went wrong and ask the owner of that plugin about its content to fix the error.

The execution of second plugin, SusImportPlugin, may fail due to its version because Ched v3.0.0 has some breaking changes.
Check the installed plugin is latest one if you are using latest Ched version.
